[SL-2530] Feature: Edit relationships
skylark-platform/skylark-ui pull request #64
Opened 2023-04-06 00:17 UTC by freixedelo

* [x] Bugfix
* [x] Feature
* [x] Refactoring
* [x] Infrastructure
* [x] Documentation

#### Jira

https://skylarkplatform.atlassian.net/browse/SL-2530

2023-04-11 21:05 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
>                        <>
<Fragment key={obj.uid}>

2023-04-11 21:05 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
>                        <>
`<Fragment key={obj.uid>`

2023-04-11 21:05 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
> +                            data-testid={`panel-object-content-item-${
not sure we need this data-testid ?

2023-04-11 21:05 UTC, james-wallis commented on src/components/toast/toast.component.tsx
> +        className="absolute top-1 right-2"
try top-2 it looked a bit close to the top

2023-04-11 21:05 UTC, james-wallis commented on src/constants/skylark.ts
> +// export const DROPPABLE_RELATIONSHIPS_ID = "droppable-relationships";
remove

2023-04-11 21:05 UTC, james-wallis commented on src/hooks/useGetObjectRelationships.ts
> +    relationships: objectOperations?.relationships,
keep this if its used

2023-04-11 21:05 UTC, james-wallis commented on src/hooks/useUpdateObjectRelationships.tsx
> +      return skylarkRequest<GQLSkylarkUpdateObjectContentResponse>(
`GQLSkylarkUpdateObjectContentResponse`
This should be specific to the relationship response

2023-04-12 08:49 UTC, freixedelo commented on src/components/panel/panel.component.tsx
> +          toast(
cannot return toast inside `useffect`, could use` return;` tho. but i want to run these commands at the end of everything:
```
setEditMode(true);
clearDroppedObject && clearDroppedObject();
```

2023-04-12 08:51 UTC, freixedelo commented on src/components/panel/panelSections/panelRelationships.component.tsx
> +    relationships = [],
`relationships` is the array of relationships to this particular object. i'm setting the default to an empty array when is `null` so don't need to check if is `null` every time.

2023-04-12 08:54 UTC, freixedelo commented on src/hooks/useGetObjectRelationships.ts
> +    relationships: objectOperations?.relationships,
it is

2023-04-12 09:02 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
> +    relationships = [],
Fair

2023-04-12 11:13 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
> +            const o = objects.filter((obj) => obj.uid !== removeUid);
prefer `const filteredObjects`

2023-04-12 11:18 UTC, james-wallis requested changes

2023-04-12 11:18 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
> +            const o = objects.filter((obj) => obj.uid !== removeUid);
and remove comment

2023-04-12 11:18 UTC, james-wallis commented on src/components/panel/panelSections/panelRelationships.component.tsx
>                        <>
please do this to remove the console error about things not having keys

2023-04-12 11:18 UTC, james-wallis commented on src/lib/graphql/skylark/dynamicMutations.ts
> +          [object.name.toLowerCase()]: {
This should be `object.argName`

2023-04-12 11:18 UTC, james-wallis commented on src/lib/graphql/skylark/dynamicMutations.ts
> +          [object.name.toLowerCase()]: {
`object.operations.update.argName`

2023-04-12 13:26 UTC, freixedelo commented on src/lib/graphql/skylark/dynamicMutations.ts
> +          [object.name.toLowerCase()]: {
doesn't work apply this change

2023-04-12 13:51 UTC, james-wallis approved these changes
Nice work!

2023-04-12 15:49 UTC, merged